name: CI/CD for Machine Learning Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run unit tests
      run: |
        pytest tests/

    - name: Execute notebook
      run: |
        jupyter nbconvert --to notebook --execute notebooks/XGB_regress.ipynb --output executed_XGB_regress.ipynb

    - name: Save model
      run: |
        python scripts/save_model.py
      if: success()

    - name: Deploy model
      run: |
        python scripts/deploy_model.py
      if: success()
